a=int(input("Enter first number :"))
b=int(input("Enter second number:"))
print("******* Comparison Operators *******")
print("Is equals :",a==b)
print("Is not equals:",a!=b)
print("Greatar than:",a>b)
print("Less than :",a<b)
print("Less than or equals:",a<=b)
print("Greater than or equal:",a>=b)
